<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>59ae4d68-ec1a-4181-9a2d-64f56732393e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../ServiceDefaults/BookingSystem.ServiceDefaults/BookingSystem.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="12.35.1" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.7.0" />
  </ItemGroup>
</Project>
